steps:
  # Build an image
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
        ".",
      ]
  # Run database migrations
  - id: "migration"
    name: "gcr.io/cloud-builders/npm"
    entrypoint: npx
    env:
      - DATABASE_URL=$_DATABASE_URL
    args:
      - "prisma"
      - "migrate"
      - "deploy"
# Push the image to artifact registry
images:
  - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}"
