steps:
  # Build an image
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]

  # Install prisma v4.16.2
  - id: "install-prisma"
    name: "node"
    entrypoint: npm
    args: ["install", "prisma@4.16.2"]

  # Run database migrations
  - id: "migration"
    name: "node"
    entrypoint: npx
    secretEnv:
      - DATABASE_URL
    args: ["prisma", "migrate", "deploy"]

# Push the image to artifact registry
images:
  - "${_IMAGE_NAME}"

options:
  pool:
    name: projects/$PROJECT_ID/locations/us-central1/workerPools/vw-private-pool
  dynamic_substitutions: true

substitutions:
  _DATABASE_URL: DATABASE_URL

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_URL}/versions/latest
      env: DATABASE_URL
